import Head from 'next/head';
import styles from './redeem-cards.module.css';

export default function PurchaseCards() {
  return (
    <>
      <Head>
        <title>Redeem Cards Degen Lotto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.home}></section>
    </>
  );
}
